services:
  db:
    image: mysql:9.1.0
    platform: linux/amd64
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      TZ: Europe/Lisbon
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_USER: docker
      MYSQL_PASSWORD: rootroot
      MYSQL_DATABASE: docker_bd
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - carlos-network
  spring-boot-starter-data-jpa:
    image: kkosmico/curso-java
    restart: always
    build: ./rest-with-spring-boot-and-java
    working_dir: /rest-with-spring-boot-and-java
    environment:
      TZ: Europe/Lisbon
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/docker_bd?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: rootroot
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    command: mvn spring-boot:run
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - carlos-network
networks:
  carlos-network:
    driver: bridge

