server:
  port: 80
cors:
  originPatterns: http://localhost:8080,http://localhost:5173

file:
  upload-dir: /Users/sousa/Documents/CursoOnlineComprado/UploadDir

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 86400000          # 1 Dia em milissegundos
      refresh-expire-length: 604800000 # 1 Semana (7 Dias) em milissegundos

email:
  subject: "Default Subject"
  message: "Default Message"

spring:
  application:
    name: curse-java

#echo $JDBC_URL
#docker image ls
#mvn clean package OR mvn clean package -f rest-with-spring-boot-and-java/pom.xml
#Comandos correctos para AWS devido ao mac M3
#aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891048843252.dkr.ecr.us-east-1.amazonaws.com 
#DOCKER_DEFAULT_PLATFORM=linux/amd64 docker compose up -d --build
#docker tag 6bea4a6f3bf1 891048843252.dkr.ecr.us-east-1.amazonaws.com/carlos/curso-java:latest
#docker push 891048843252.dkr.ecr.us-east-1.amazonaws.com/carlos/curso-java:latest

#Comando para sacar definitions
#aws ecs describe-task-definition --task-definition task-carlos-java-curse --query taskDefinition > task-definition.json
#open -e task-definition.json

  datasource:
    #url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/spring_boot_starter_data_jpa?useTimezone=true&serverTimezone=UTC}
    #url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/docker_bd?useTimezone=true&serverTimezone=UTC}
    #url: ${SPRING_DATASOURCE_URL:jdbc:mysql://carlos-aws-db.cch2c88mqoc5.us-east-1.rds.amazonaws.com/aws_db?useTimezone=true&serverTimezone=UTC}
    url: ${JDBC_URL}       
    username: ${SPRING_DATASOURCE_USERNAME:root}
    #password: ${SPRING_DATASOURCE_PASSWORD:rootroot}
    password: ${SPRING_DATASOURCE_PASSWORD:Admin123}
  
  flyway:
    enabled: true
    locations: classpath:db/migration
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

logging:
  level:
    root: INFO
    #net.sf.jasperreports.engine.*: TRACE

springdoc:
  paths-to-scan:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: method
    use-root-path: true
